# Generated by Django 5.2 on 2025-04-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(blank=True)),
                ('last_name', models.CharField(blank=True)),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
